export const domainesExpertisme = [
  { value: "Full Stack Developer", label: "Full Stack Developer" },
  { value: "Frontend Developer", label: "Frontend Developer" },
  { value: "Backend Developer", label: "Backend Developer" },
  { value: "DevOps Engineer", label: "DevOps Engineer" },
  { value: "Data Scientist", label: "Data Scientist" },
  { value: "Machine Learning Engineer", label: "Machine Learning Engineer" },
  { value: "Cybersecurity Analyst", label: "Cybersecurity Analyst" },
  { value: "Network Engineer", label: "Network Engineer" },
  { value: "Cloud Solutions Architect", label: "Cloud Solutions Architect" },
  { value: "UI/UX Designer", label: "UI/UX Designer" },
  { value: "Database Administrator", label: "Database Administrator" },
  { value: "IT Project Manager", label: "IT Project Manager" },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Quality Assurance Engineer", label: "Quality Assurance Engineer" },
  { value: "Mobile App Developer", label: "Mobile App Developer" },
  { value: "Systems Analyst", label: "Systems Analyst" },
  { value: "Game Developer", label: "Game Developer" },
  { value: "Blockchain Developer", label: "Blockchain Developer" },
  {
    value: "Artificial Intelligence Engineer",
    label: "Artificial Intelligence Engineer",
  },
  { value: "Embedded Systems Engineer", label: "Embedded Systems Engineer" },
  { value: "IT Support Specialist", label: "IT Support Specialist" },
  { value: "Network Security Engineer", label: "Network Security Engineer" },
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "Web Designer", label: "Web Designer" },
  { value: "Big Data Engineer", label: "Big Data Engineer" },
  { value: "E-commerce Developer", label: "E-commerce Developer" },
  { value: "Robotics Engineer", label: "Robotics Engineer" },
];

export const expertismeLvl = [
  { value: "Beginner", label: "Beginner" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Advanced", label: "Advanced" },
];
