export const skills = [
  { value: "JavaScript", label: "JavaScript" },
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "C++", label: "C++" },
  { value: "C#", label: "C#" },
  { value: "Ruby", label: "Ruby" },
  { value: "PHP", label: "PHP" },
  { value: "Swift", label: "Swift" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Go", label: "Go" },
  { value: "Rust", label: "Rust" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "SQL", label: "SQL" },
  { value: "HTML", label: "HTML" },
  { value: "CSS", label: "CSS" },
  { value: "ReactJS", label: "ReactJS" },
  { value: "Angular", label: "Angular" },
  { value: "Vue.js", label: "Vue.js" },
  { value: "Node.js", label: "Node.js" },
  { value: "Express.js", label: "Express.js" },
  { value: "Django", label: "Django" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Laravel", label: "Laravel" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "Flask", label: "Flask" },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "RESTful APIs", label: "RESTful APIs" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "MySQL", label: "MySQL" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Git", label: "Git" },
  { value: "Docker", label: "Docker" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "AWS", label: "AWS" },
  { value: "Azure", label: "Azure" },
  { value: "Google Cloud", label: "Google Cloud" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "CI/CD", label: "CI/CD" },
  { value: "Agile Methodologies", label: "Agile Methodologies" },
  { value: "Scrum", label: "Scrum" },
  { value: "Kanban", label: "Kanban" },
  { value: "Test-Driven Development", label: "Test-Driven Development" },
  { value: "Continuous Integration", label: "Continuous Integration" },
  { value: "Continuous Delivery", label: "Continuous Delivery" },
  { value: "Microservices", label: "Microservices" },
  { value: "Serverless Architecture", label: "Serverless Architecture" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Data Science", label: "Data Science" },
  { value: "Big Data", label: "Big Data" },
  { value: "Blockchain", label: "Blockchain" },
  { value: "IoT (Internet of Things)", label: "IoT (Internet of Things)" },
  { value: "AR/VR Development", label: "AR/VR Development" },
  { value: "Ethical Hacking", label: "Ethical Hacking" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "DevOps", label: "DevOps" },
  { value: "Full Stack Development", label: "Full Stack Development" },
  { value: "Frontend Development", label: "Frontend Development" },
  { value: "Backend Development", label: "Backend Development" },
  { value: "Mobile App Development", label: "Mobile App Development" },
  { value: "Web Development", label: "Web Development" },
  { value: "Game Development", label: "Game Development" },
  { value: "UI/UX Design", label: "UI/UX Design" },
  { value: "Responsive Design", label: "Responsive Design" },
  { value: "Version Control", label: "Version Control" },
];
