export enum ExperienceLevel {
  Beginner = "Beginner",
  Intermediate = "Intermediate",
  Advanced = "Advanced",
}

export enum Category {
  WebDevelopment = "Web Development",
  MobileDevelopment = "Mobile Development",
  UXUIDesign = "UX/UI Design",
  DataScience = "Data Science",
  Cybersecurity = "Cybersecurity",
  CloudComputing = "Cloud Computing",
  ArtificialIntelligence = "Artificial Intelligence",
  GameDevelopment = "Game Development",
  DevOps = "DevOps",
  FrontendDevelopment = "Frontend Development",
  BackendDevelopment = "Backend Development",
  FullStackDevelopment = "Full Stack Development",
  UIUXDesign = "UI/UX Design",
  ProductManagement = "Product Management",
  SoftwareEngineering = "Software Engineering",
  DatabaseAdministration = "Database Administration",
  MobileAppDevelopment = "Mobile App Development",
  WebDesign = "Web Design",
  NetworkAdministration = "Network Administration",
  SystemAdministration = "System Administration",
  DataEngineering = "Data Engineering",
  CloudArchitecture = "Cloud Architecture",
  NaturalLanguageProcessing = "Natural Language Processing",
  Robotics = "Robotics",
  AugmentedReality = "Augmented Reality",
  VirtualReality = "Virtual Reality",
  Blockchain = "Blockchain",
  InternetOfThings = "Internet of Things (IoT)",
  DevSecOps = "DevSecOps",
  GameDesign = "Game Design",
  QualityAssurance = "Quality Assurance (QA)",
  FrontendFrameworks = "Frontend Frameworks",
  BackendFrameworks = "Backend Frameworks",
  MobileFrameworks = "Mobile Frameworks",
  UIUXFrameworks = "UI/UX Frameworks",
  MachineLearning = "Machine Learning",
  DeepLearning = "Deep Learning",
  ComputerVision = "Computer Vision",
  CloudServices = "Cloud Services",
  DataAnalytics = "Data Analytics",
  CyberthreatAnalysis = "Cyberthreat Analysis",
  NetworkSecurity = "Network Security",
  CloudSecurity = "Cloud Security",
  AIEthics = "AI Ethics",
  Bioinformatics = "Bioinformatics",
  QuantumComputing = "Quantum Computing",
  HumanComputerInteraction = "Human-Computer Interaction (HCI)",
  EmbeddedSystems = "Embedded Systems",
}

export enum TypesTask {
  ToDo = "To Do",
  InProgress = "In progress",
  Done = "Done",
}

// new / complited / Cancelled

export enum StatusOrder {
  NEW = "new",
  COMPLITED = "complited",
  CANCELLED = "cancelled",
}
